config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/order-products', to: 'home#order_products', as: :order_products
  get '/add-to-cart/:cart_id/:id', to: 'home#add_to_cart', as: :add_to_cart
  delete '/remove-from-cart/:cart_id/:id', to: 'home#remove_from_cart', as: :remove_from_cart
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
require 'faker'
class Cart
  attr_accessor :id, :product_ids, :current_products
  def initialize(id = nil)
    if id.nil?
      self.id = Faker::Number.number(10)
    else
      self.id = id
    end
    self.product_ids ||= []
  end

  def empty?
    self.product_ids.blank?
  end

  def products
    self.product_ids.map do |product_id|
      Product.find(product_id)
    end
  end

  def remove_product(product_id)
    return false unless self.product_ids.include?(product_id)
    self.product_ids.delete_at(self.product_ids.index(product_id))
  end

  def total_with_freight
    total + freight
  end

  def total
    products.sum(&:price)
  end

  def freight
    return 0 if total > 250
    10*product_ids.count
  end
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, :price, :score, presence: true
  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  helper_method :current_cart
  before_action :set_products, only: [:index, :order_products, :add_to_cart, :remove_from_cart]
  def index
    session[:product_ids] = []
    # session[:product_ids] = Product.ids
    # current_cart.product_ids = session[:product_ids]
  end

  def order_products
    respond_to do |format|
      format.html { head :no_content }
      format.js { render action: 'order_products' }
    end
  end

  def add_to_cart
    session[:product_ids] ||= []
    session[:product_ids] << params[:id]
    current_cart.product_ids = session[:product_ids]
    respond_to do |format|
      format.html { head :no_content }
      format.js { render action: 'reload_cart' }
    end
  end

  def remove_from_cart
    current_cart.product_ids = session[:product_ids]
    current_cart.remove_product(params[:id])
    session[:product_ids] = current_cart.product_ids
    respond_to do |format|
      format.html { head :no_content }
      format.js { render action: 'reload_cart' }
    end
  end

  protected
    def current_cart
      @current_cart ||= Cart.new(params[:cart_id])
    end

    def set_products
      @products = Product.order(params[:order] || :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def orders_for_products
    {
      t('home.index.order.by_name') => :name,
      t('home.index.order.by_score') => :score,
      t('home.index.order.by_price') => :price
    }
  end
  
end

app/views/home/_cart.html.haml
- if current_cart.empty?
  .empty_cart
    %h1=t('.cart_title')
    .place_holder
      =image_tag 'cart-icon.svg'
      %h3=t('.empty_cart')
- else
  .cart_with_items
    %h4=t('.cart_title_with_products', count: current_cart.products.count)
    - current_cart.products.each do |product|
      .cart_item
        .image
          =image_tag url_for(product.image)
        .description
          .title=product.name
          .price=number_to_currency product.price
        .actions
          .action_background
            =link_to 'x', remove_from_cart_path(current_cart.id, product.id, order: params[:order]), remote: true, class: 'remove_from_cart', method: :delete
    .total_with_freight
      .title=t('.subtotal')
      .value=number_to_currency(current_cart.total)
    .total_freight
      .title=t('.freight')
      .value=number_to_currency(current_cart.freight)
    .cart_total
      .title=t('.total')
      .value=number_to_currency(current_cart.total_with_freight)
    .finalize_purchase=link_to(t('.finalize_purchase'), root_path)

app/views/home/_products_list.html.haml
- @products.in_groups_of(3).each do |products|
    .products
        = render products

app/views/home/add_to_cart.js.erb
$('.cart').html("<%= j render 'home/cart', locals: {count: current_cart.product_ids} %>");
$('.products_list').html("<%= j render 'home/products_list' %>");
$('.description').hover(function() {
  $(this).next('.add_to_cart').show();
});

app/views/home/index.html.haml
.central_container
  .header
    .title
      %h1=t('.title')
    .products_order
      =select_tag(:product_order, options_for_select(orders_for_products), data: {action: order_products_path})
  .products_list
    = render partial: 'products_list'
.cart
  = render partial: 'cart'
  

app/views/home/order_products.js.erb
<%= render 'home/products_list' %>

app/views/home/reload_cart.js.erb
$('.cart').html("<%= j render 'home/cart', locals: {count: current_cart.product_ids} %>");
$('.products_list').html("<%= j render 'home/products_list' %>");
$('.description').hover(function() {
  $(this).next('.add_to_cart').show();
});

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Rtoledocart
    = csrf_meta_tags
    = csp_meta_tag
    %link{href: "//fonts.googleapis.com/css?family=Open+Sans:400,700", rel: "stylesheet", type: "text/css"}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container=yield
    

app/views/products/_product.html.haml
.product
  .image_placeholder=image_tag url_for(product.image)
  .description
    .title
      = product.name
    .price
      = number_to_currency product.price
  =link_to t('home.add_to_cart.title'), add_to_cart_path(current_cart.id,product, order: params[:order]), remote: true, class: 'add_to_cart'